version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=wine_ecommerce_db
      - POSTGRES_USER=wine-admin
      - POSTGRES_PASSWORD=wine-secret
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db_data:/var/lib/postgresql/data

  db_client:
      image: admirer
      restart: always
      ports:
        - 8080:8080

  web:
    # restart: always
    build:
        context: ./wine_ecommerce
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wine_ecommerce:/wine_ecommerce
    ports:
      - '8000:8000'
    depends_on:
      - db

  tests:
    build:
        context: ./wine_ecommerce
        dockerfile: Dockerfile
    command: ["python", "manage.py", "test", "shop"]
    volumes:
      - ./wine_ecommerce:/wine_ecommerce
    depends_on:
      - db

# volumes:
#   db_data:
    # external: true
