version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=wine-db
      - POSTGRES_USER=wine-admin
      - POSTGRES_PASSWORD=wine-secret
      - PGDATA=/django-data
    volumes:
      - ./db_data:/django-data

  db_client:
      image: adminer
      restart: always
      ports:
        - 8080:8080

  web:
    # restart: always
    build:
        context: ./wine_ecommerce
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wine_ecommerce:/django-app
    ports:
      - 8000:8000
    depends_on:
      - db

  tests:
    build:
        context: ./wine_ecommerce
        dockerfile: Dockerfile
    command: ["python", "manage.py", "test", "shop"]
    volumes:
      - ./wine_ecommerce:/django-app
    depends_on:
      - db

# volumes:
#   db_data:
    # external: true
